In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df = pd.read_excel("/content/jester-data-1.xls", header=None)
df

0      1      2      3      4     5      6     7     8      9    ...  \
0       74  -7.82   8.79  -9.66  -8.16 -7.52  -8.50 -9.85  4.17  -8.98  ...   
1      100   4.08  -0.29   6.36   4.37 -2.38  -9.66 -0.73 -5.34   8.88  ...   
2       49  99.00  99.00  99.00  99.00  9.03   9.27  9.03  9.27  99.00  ...   
3       48  99.00   8.35  99.00  99.00  1.80   8.16 -2.82  6.21  99.00  ...   
4       91   8.50   4.61  -4.17  -5.39  1.36   1.60  7.04  4.61  -0.44  ...   
...    ...    ...    ...    ...    ...   ...    ...   ...   ...    ...  ...   
24978  100   0.44   7.43   9.08   2.33  3.20   6.75 -8.79 -0.53  -8.74  ...   
24979   91   9.13  -8.16   8.59   9.08  0.87  -8.93 -3.50  5.78  -8.11  ...   
24980   39  99.00  99.00  99.00  99.00 -7.77  99.00  6.70 -6.75  99.00  ...   
24981   37  99.00  99.00  99.00  99.00 -9.71  99.00  4.56 -8.30  99.00  ...   
24982   72   2.43   2.67  -3.98   4.27 -2.28   7.33  2.33  4.56   6.75  ...   

         91     92     93     94     95     96     97     98     99     100  
0       2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1       2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2      99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3      99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4       5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
24978   8.83  -1.21   9.22  -6.70   8.45   9.03   6.55   8.69   8.79   7.43  
24979  -1.17  -5.73  -1.46   0.24   9.22  -8.20  -7.23  -8.59   9.13   8.45  
24980  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24981  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24982  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  

[24983 rows x 101 columns]

In [4]:
df = df.drop(0, axis=1)

In [7]:
df = df.replace(99.00, 0)

## user2のitem1のジョーク評価を予測していく

In [9]:
df

1     2     3     4     5     6     7     8     9     10   ...   91   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2      0.00  0.00  0.00  0.00  9.03  9.27  9.03  9.27  0.00  0.00  ...  0.00   
3      0.00  8.35  0.00  0.00  1.80  8.16 -2.82  6.21  0.00  1.84  ...  0.00   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23  ...  8.83   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  ... -1.17   
24980  0.00  0.00  0.00  0.00 -7.77  0.00  6.70 -6.75  0.00  0.00  ...  0.00   
24981  0.00  0.00  0.00  0.00 -9.71  0.00  4.56 -8.30  0.00  0.00  ...  0.00   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61  ...  0.00   

        92    93    94    95    96    97    98    99    100  
0      0.00  0.00  0.00  0.00  0.00 -5.63  0.00  0.00  0.00  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2      0.00  0.00  9.08  0.00  0.00  0.00  0.00  0.00  0.00  
3      0.00  0.00  0.53  0.00  0.00  0.00  0.00  0.00  0.00  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  
24981  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  
24982  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  

[24983 rows x 100 columns]

In [10]:
cos_list = []
for user_id in df.index:
  cos_list.append(cosine_similarity([df.loc[1, 2:]], [df.loc[user_id, 2:]]))

cos_list

[array([[-0.34329462]]),
 array([[1.]]),
 array([[0.16091357]]),
 array([[0.11334082]]),
 array([[0.1658677]]),
 array([[-0.4008306]]),
 array([[0.17073908]]),
 array([[-0.26687168]]),
 array([[-0.23234124]]),
 array([[0.28388735]]),
 array([[0.10348883]]),
 array([[-0.17929191]]),
 array([[0.03847554]]),
 array([[0.47980014]]),
 array([[-0.03452211]]),
 array([[-0.15567128]]),
 array([[-0.01346404]]),
 array([[0.43420782]]),
 array([[0.17409774]]),
 array([[-0.01228717]]),
 array([[-0.18297399]]),
 array([[0.1500407]]),
 array([[0.13281597]]),
 array([[-0.04844661]]),
 array([[-0.04698994]]),
 array([[0.20372568]]),
 array([[-0.17181195]]),
 array([[-0.24894363]]),
 array([[0.02365119]]),
 array([[0.15526327]]),
 array([[0.12869902]]),
 array([[0.21638671]]),
 array([[0.2846111]]),
 array([[0.05918855]]),
 array([[0.43497009]]),
 array([[0.09184994]]),
 array([[0.28593217]]),
 array([[-0.00931616]]),
 array([[0.47208229]]),
 array([[-0.03176207]]),
 array([[-0.22565572]]),
 array([[0.

In [11]:
user_list = sorted(range(len(cos_list)), key=lambda i: cos_list[i], reverse=True)
user_list

[1,
 20217,
 16058,
 3060,
 6194,
 6286,
 6611,
 22429,
 16158,
 12519,
 19843,
 9596,
 11818,
 6215,
 24852,
 11246,
 24664,
 15003,
 19252,
 24497,
 8601,
 23036,
 16045,
 1199,
 14856,
 12244,
 10112,
 12840,
 24714,
 23801,
 3798,
 11829,
 22028,
 21589,
 11409,
 19335,
 5229,
 12944,
 22294,
 13554,
 7651,
 3266,
 14968,
 9395,
 23924,
 7610,
 11874,
 8612,
 1766,
 977,
 615,
 3924,
 5152,
 17056,
 23835,
 12850,
 14300,
 21578,
 3073,
 12257,
 12099,
 15489,
 20844,
 14055,
 24768,
 9731,
 6169,
 8986,
 18279,
 16787,
 19440,
 11990,
 3145,
 19412,
 7072,
 24922,
 1464,
 5784,
 6159,
 4114,
 207,
 18099,
 15022,
 2618,
 19264,
 11886,
 7400,
 23467,
 13926,
 23688,
 24083,
 1403,
 7254,
 2183,
 12340,
 12423,
 5333,
 13897,
 11576,
 16588,
 13491,
 22541,
 24675,
 10022,
 13925,
 14181,
 9622,
 22710,
 16802,
 11157,
 19034,
 5202,
 23447,
 4680,
 14447,
 19533,
 1431,
 8001,
 3989,
 8009,
 13009,
 3358,
 2308,
 11224,
 9297,
 23660,
 5952,
 24069,
 4428,
 14926,
 17104,
 22708,


In [12]:

weighted_sum = 0
total_weight = 0

for user_id in user_list[1:]:
  weight = cos_list[user_id]
  review_score = df.iloc[user_id][1]
  if review_score > 0:
    weighted_sum += review_score * weight
    total_weight += weight

weighted_avg = weighted_sum / total_weight
print(weighted_avg)

[[6.40850146]]


In [13]:
df

1     2     3     4     5     6     7     8     9     10   ...   91   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2      0.00  0.00  0.00  0.00  9.03  9.27  9.03  9.27  0.00  0.00  ...  0.00   
3      0.00  8.35  0.00  0.00  1.80  8.16 -2.82  6.21  0.00  1.84  ...  0.00   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23  ...  8.83   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  ... -1.17   
24980  0.00  0.00  0.00  0.00 -7.77  0.00  6.70 -6.75  0.00  0.00  ...  0.00   
24981  0.00  0.00  0.00  0.00 -9.71  0.00  4.56 -8.30  0.00  0.00  ...  0.00   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61  ...  0.00   

        92    93    94    95    96    97    98    99    100  
0      0.00  0.00  0.00  0.00  0.00 -5.63  0.00  0.00  0.00  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2      0.00  0.00  9.08  0.00  0.00  0.00  0.00  0.00  0.00  
3      0.00  0.00  0.53  0.00  0.00  0.00  0.00  0.00  0.00  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  
24981  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  
24982  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  

[24983 rows x 100 columns]