In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df = pd.read_csv("https://files.grouplens.org/datasets/movielens/ml-100k/u.data", names=["user_id", "item_id", "review", "timestamp"], sep="\t")

In [4]:
df = pd.pivot_table(df.drop("timestamp", axis=1), index="user_id", columns="item_id", values="review")

In [5]:
df = df.fillna(0)

In [6]:
df

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5         4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940       0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943       0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [7]:
cos_list = []
for user_id in df.index:
  cos_list.append(cosine_similarity([df.loc[2, 2:]], [df.loc[user_id, 2:]]))
cos_list

[array([[0.15834506]]),
 array([[1.]]),
 array([[0.11156787]]),
 array([[0.17969404]]),
 array([[0.06123455]]),
 array([[0.23894671]]),
 array([[0.10827612]]),
 array([[0.10425672]]),
 array([[0.16246959]]),
 array([[0.15239262]]),
 array([[0.13039886]]),
 array([[0.12233863]]),
 array([[0.2211191]]),
 array([[0.22876043]]),
 array([[0.45547941]]),
 array([[0.11430938]]),
 array([[0.20005843]]),
 array([[0.17121885]]),
 array([[0.10226895]]),
 array([[0.04397371]]),
 array([[0.19105808]]),
 array([[0.06501167]]),
 array([[0.13416312]]),
 array([[0.17989739]]),
 array([[0.13282542]]),
 array([[0.43889476]]),
 array([[0.18671165]]),
 array([[0.1033602]]),
 array([[0.17666104]]),
 array([[0.23210951]]),
 array([[0.0825981]]),
 array([[0.2179398]]),
 array([[0.16868044]]),
 array([[0.21436576]]),
 array([[0.07626947]]),
 array([[0.10795673]]),
 array([[0.08052554]]),
 array([[0.0444299]]),
 array([[0.27085974]]),
 array([[0.25381427]]),
 array([[0.10898791]]),
 array([[0.10528266]]),
 arra

In [8]:
user_list = sorted(range(len(cos_list)), key=lambda i: cos_list[i], reverse=True)

In [9]:
user_list


[1,
 700,
 930,
 459,
 103,
 130,
 412,
 14,
 833,
 734,
 485,
 25,
 305,
 623,
 767,
 568,
 936,
 742,
 716,
 62,
 462,
 265,
 677,
 519,
 525,
 343,
 128,
 893,
 925,
 295,
 110,
 633,
 438,
 78,
 732,
 276,
 422,
 650,
 443,
 191,
 481,
 918,
 696,
 868,
 859,
 239,
 873,
 156,
 573,
 323,
 935,
 547,
 208,
 672,
 148,
 359,
 463,
 328,
 170,
 469,
 615,
 474,
 589,
 344,
 107,
 135,
 111,
 790,
 719,
 919,
 909,
 836,
 46,
 764,
 484,
 115,
 112,
 524,
 364,
 783,
 667,
 180,
 769,
 431,
 472,
 226,
 283,
 826,
 793,
 53,
 67,
 636,
 189,
 73,
 219,
 178,
 175,
 878,
 409,
 563,
 862,
 551,
 427,
 802,
 937,
 355,
 799,
 423,
 593,
 460,
 419,
 203,
 44,
 723,
 138,
 132,
 673,
 595,
 808,
 415,
 303,
 817,
 741,
 596,
 399,
 140,
 844,
 228,
 543,
 42,
 190,
 682,
 610,
 264,
 445,
 890,
 934,
 204,
 65,
 184,
 781,
 753,
 333,
 586,
 437,
 643,
 389,
 855,
 546,
 516,
 897,
 293,
 679,
 391,
 172,
 630,
 591,
 429,
 594,
 466,
 702,
 256,
 539,
 413,
 739,
 894,
 786,
 905,
 143,

In [10]:
weighted_sum = 0
total_weight = 0
for user_id in user_list[1:]:
  weight = cos_list[user_id]
  review_score = df.iloc[user_id][1]
  if review_score > 0:
    weighted_sum += review_score * weight
    total_weight += weight

print(weighted_sum)
print(total_weight)
weighted_avg = weighted_sum / total_weight
print(weighted_avg)

[[319.7689028]]
[[83.62510132]]
[[3.82383875]]


##  欠損値を0埋めではなくてUserごとの平均値で埋める

In [41]:
df = pd.read_csv("https://files.grouplens.org/datasets/movielens/ml-100k/u.data", names=["user_id", "item_id", "review", "timestamp"], sep="\t")
df = pd.pivot_table(df.drop("timestamp", axis=1), index="user_id", columns="item_id", values="review")

df


item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5         4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940       NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941       5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943       NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

In [42]:
# ユーザー2のアイテム1の評価を一時的に保存してNanで埋める
user2_item1_review = df.loc[2, 1]
df.loc[2, 1] = np.nan

# 平均値埋め
df = df.apply(lambda x:x.fillna(x.mean()), axis=1)


In [43]:
# ユーザー2のアイテム1の評価を元に戻す
df.loc[2, 1] = user2_item1_review


item_id      1         2         3         4         5         6         7     \
user_id                                                                         
1        5.000000  3.000000  4.000000  3.000000  3.000000  5.000000  4.000000   
2        4.000000  3.704918  3.704918  3.704918  3.704918  3.704918  3.704918   
3        2.796296  2.796296  2.796296  2.796296  2.796296  2.796296  2.796296   
4        4.333333  4.333333  4.333333  4.333333  4.333333  4.333333  4.333333   
5        4.000000  3.000000  2.874286  2.874286  2.874286  2.874286  2.874286   
...           ...       ...       ...       ...       ...       ...       ...   
939      4.265306  4.265306  4.265306  4.265306  4.265306  4.265306  4.265306   
940      3.457944  3.457944  3.457944  2.000000  3.457944  3.457944  4.000000   
941      5.000000  4.045455  4.045455  4.045455  4.045455  4.045455  4.000000   
942      4.265823  4.265823  4.265823  4.265823  4.265823  4.265823  4.265823   
943      3.410714  5.000000  3.410714  3.410714  3.410714  3.410714  3.410714   

item_id      8         9         10    ...      1673      1674      1675  \
user_id                                ...                                 
1        1.000000  5.000000  3.000000  ...  3.610294  3.610294  3.610294   
2        3.704918  3.704918  2.000000  ...  3.704918  3.704918  3.704918   
3        2.796296  2.796296  2.796296  ...  2.796296  2.796296  2.796296   
4        4.333333  4.333333  4.333333  ...  4.333333  4.333333  4.333333   
5        2.874286  2.874286  2.874286  ...  2.874286  2.874286  2.874286   
...           ...       ...       ...  ...       ...       ...       ...   
939      4.265306  5.000000  4.265306  ...  4.265306  4.265306  4.265306   
940      5.000000  3.000000  3.457944  ...  3.457944  3.457944  3.457944   
941      4.045455  4.045455  4.045455  ...  4.045455  4.045455  4.045455   
942      4.265823  4.265823  4.265823  ...  4.265823  4.265823  4.265823   
943      3.410714  3.000000  3.410714  ...  3.410714  3.410714  3.410714   

item_id      1676      1677      1678      1679      1680      1681      1682  
user_id                                                                        
1        3.610294  3.610294  3.610294  3.610294  3.610294  3.610294  3.610294  
2        3.704918  3.704918  3.704918  3.704918  3.704918  3.704918  3.704918  
3        2.796296  2.796296  2.796296  2.796296  2.796296  2.796296  2.796296  
4        4.333333  4.333333  4.333333  4.333333  4.333333  4.333333  4.333333  
5        2.874286  2.874286  2.874286  2.874286  2.874286  2.874286  2.874286  
...           ...       ...       ...       ...       ...       ...       ...  
939      4.265306  4.265306  4.265306  4.265306  4.265306  4.265306  4.265306  
940      3.457944  3.457944  3.457944  3.457944  3.457944  3.457944  3.457944  
941      4.045455  4.045455  4.045455  4.045455  4.045455  4.045455  4.045455  
942      4.265823  4.265823  4.265823  4.265823  4.265823  4.265823  4.265823  
943      3.410714  3.410714  3.410714  3.410714  3.410714  3.410714  3.410714  

[943 rows x 1682 columns]

In [44]:
cos_list = []
for user_id in df.index:
  cos_list.append(cosine_similarity([df.loc[2, 2:]], [df.loc[user_id, 2:]]))

user_list = sorted(range(len(cos_list)), key=lambda i: cos_list[i], reverse=True)

weighted_sum = 0
total_weight = 0
for user_id in user_list[1:]:
  weight = cos_list[user_id]
  review_score = df.iloc[user_id][1]
  if review_score > 0:
    weighted_sum += review_score * weight
    total_weight += weight

print(weighted_sum)
print(total_weight)
weighted_avg = weighted_sum / total_weight
print(weighted_avg)

[[3500.72883172]]
[[938.06721043]]
[[3.73185289]]
