In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("https://files.grouplens.org/datasets/movielens/ml-100k/u.data")
df

196\t242\t3\t881250949
0       186\t302\t3\t891717742
1        22\t377\t1\t878887116
2        244\t51\t2\t880606923
3       166\t346\t1\t886397596
4       298\t474\t4\t884182806
...                        ...
99994   880\t476\t3\t880175444
99995   716\t204\t5\t879795543
99996  276\t1090\t1\t874795795
99997    13\t225\t2\t882399156
99998    12\t203\t3\t879959583

[99999 rows x 1 columns]

In [3]:
df = pd.read_csv("https://files.grouplens.org/datasets/movielens/ml-100k/u.data", names=["user_id", "item_id", "review", "timestamp"], sep="\t")
df

user_id  item_id  review  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [4]:
df = pd.pivot_table(df.drop("timestamp", axis=1), index="user_id", columns="item_id", values="review")
df

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5         4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940       NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941       5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943       NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

In [5]:
df = df.fillna(0)
df

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5         4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940       0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943       0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [6]:
## cos類似度をnumpyを使って計算


dot = np.dot(df.iloc[0], df.iloc[1])

norm_a = np.linalg.norm(df.iloc[0])
norm_b = np.linalg.norm(df.iloc[1])

dot / (norm_a*norm_b)

0.16693098386870195

In [7]:
cosine_similarity([df.iloc[0]], [df.iloc[1]])

array([[0.16693098]])

## user_id=2 item_id=1のレビューを予測しよう！

In [8]:
df

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5         4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940       0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943       0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [9]:
df.loc[2, 2:]

item_id
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
       ... 
1678    0.0
1679    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 2, Length: 1681, dtype: float64

In [10]:
cos_list = []
for user_id in df.index:
  cos_list.append(cosine_similarity([df.loc[2, 2:]], [df.loc[user_id, 2:]]))
cos_list

[array([[0.15834506]]),
 array([[1.]]),
 array([[0.11156787]]),
 array([[0.17969404]]),
 array([[0.06123455]]),
 array([[0.23894671]]),
 array([[0.10827612]]),
 array([[0.10425672]]),
 array([[0.16246959]]),
 array([[0.15239262]]),
 array([[0.13039886]]),
 array([[0.12233863]]),
 array([[0.2211191]]),
 array([[0.22876043]]),
 array([[0.45547941]]),
 array([[0.11430938]]),
 array([[0.20005843]]),
 array([[0.17121885]]),
 array([[0.10226895]]),
 array([[0.04397371]]),
 array([[0.19105808]]),
 array([[0.06501167]]),
 array([[0.13416312]]),
 array([[0.17989739]]),
 array([[0.13282542]]),
 array([[0.43889476]]),
 array([[0.18671165]]),
 array([[0.1033602]]),
 array([[0.17666104]]),
 array([[0.23210951]]),
 array([[0.0825981]]),
 array([[0.2179398]]),
 array([[0.16868044]]),
 array([[0.21436576]]),
 array([[0.07626947]]),
 array([[0.10795673]]),
 array([[0.08052554]]),
 array([[0.0444299]]),
 array([[0.27085974]]),
 array([[0.25381427]]),
 array([[0.10898791]]),
 array([[0.10528266]]),
 arra

In [17]:
def f1(i):
  return i*2

f2 = lambda i: cos_list[i]
f2(0)

# lambda i: cos_list[i]

array([[0.15834506]])

In [20]:
# sorted([ソートの対象], key=[ソートキー], reverse=True,False)
cos_list = sorted(range(len(cos_list)), key=lambda i: cos_list[i], reverse=True)[:51]

In [32]:
df_sim50 = df.iloc[cos_list[1:]]
df_sim50

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
701       4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
931       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
460       2.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   3.0   3.0  ...   
104       0.0   0.0   3.0   0.0   0.0   0.0   3.0   0.0   2.0   2.0  ...   
131       4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
413       0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...   
15        1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   4.0   0.0  ...   
834       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   3.0   0.0  ...   
735       4.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...   
486       4.0   0.0   2.0   0.0   0.0   4.0   5.0   0.0   5.0   4.0  ...   
26        3.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...   
306       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
624       4.0   0.0   3.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
768       5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
569       4.0   0.0   1.0   0.0   0.0   0.0   4.0   0.0   5.0   0.0  ...   
937       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
743       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
717       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
63        3.0   0.0   2.0   0.0   0.0   3.0   0.0   0.0   0.0   4.0  ...   
463       1.0   0.0   2.0   0.0   0.0   0.0   4.0   0.0   0.0   1.0  ...   
266       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0  ...   
678       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
520       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
526       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
344       3.0   0.0   0.0   4.0   3.0   0.0   4.0   5.0   5.0   0.0  ...   
129       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
894       4.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   4.0   4.0  ...   
926       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
296       5.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   4.0   2.0  ...   
111       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
634       3.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   5.0   0.0  ...   
439       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
79        4.0   0.0   0.0   0.0   0.0   4.0   5.0   0.0   0.0   5.0  ...   
733       2.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   3.0   3.0  ...   
277       4.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0   4.0   0.0  ...   
423       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   4.0  ...   
651       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
444       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
192       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   5.0   0.0  ...   
482       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
919       4.0   0.0   0.0   1.0   4.0   0.0   3.0   0.0   5.0   0.0  ...   
697       5.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   4.0   0.0  ...   
869       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
860       0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
240       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
874       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
157       5.0   0.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
574       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
324       5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
936       4.0   0.0   4.0   0.0   0.0   5.0   4.0   0.0   4.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  16

In [36]:
df_sim50[df_sim50[1] != 0.0][1].mean()

3.730769230769231

In [37]:
df

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5         4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940       0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943       0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]